export const GET_NETFLIT_ORIGINALS = 'GET_NETFLIT_ORIGINALS';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_TOPRATED_MOVIES = 'GET_TOPRATED_MOVIES';
export const GET_COMEDY_MOVIES = 'GET_COMEDY_MOVIES';
export const GET_HORROR_MOVIES = 'GET_HORROR_MOVIES';
export const GET_DOCUMENT_MOVIES = 'GET_DOCUMENT_MOVIES';
export const GET_ROMANCE_MOVIES = 'GET_ROMANCE_MOVIES';
export const GET_ACTIONS_MOVIES = 'GET_ACTIONS_MOVIES';

export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL'